Repository Next-Flip/Momentum-Firmware, pull requests merged in 2024-10, with the labels that each got.

#240 New MNTM Specific Universal Remote Additions
  CHANGELOG.md
  applications/main/infrared/resources/infrared/assets/digital_sign.ir
  applications/main/infrared/resources/infrared/assets/led.ir
  applications/main/infrared/resources/infrared/assets/monitor.ir
Labels: enhancement

#245 Bresser 3CH protocol: added V0 message format
  CHANGELOG.md
  applications/debug/unit_tests/resources/unit_tests/subghz/bresser_3ch_v0.sub
  applications/debug/unit_tests/resources/unit_tests/subghz/bresser_3ch_v0_raw.sub
  applications/debug/unit_tests/tests/subghz/subghz_test.c
  lib/subghz/protocols/bresser_3ch.c
Labels: enhancement

#246 Sub-GHz: Fix GPS "Latitute" typo, switch to "Lat" and "Lon" in .sub files
  CHANGELOG.md
  applications/main/subghz/subghz_i.c
  lib/subghz/blocks/generic.c
Labels: bugfix

#244 Power: Suppress Shutdown on Idle While Charging / Plugged In
  CHANGELOG.md
  applications/services/power/power_service/power.c
Labels: bugfix

#250 [IR] Bluray/DVD Universal Remote
  CHANGELOG.md
  applications/main/infrared/resources/infrared/assets/bluray_dvd.ir
  applications/main/infrared/scenes/infrared_scene_config.h
  applications/main/infrared/scenes/infrared_scene_universal.c
  applications/main/infrared/scenes/infrared_scene_universal_bluray.c
  assets/icons/Infrared/eject_19x20.png
  assets/icons/Infrared/eject_hover_19x20.png
  assets/icons/Infrared/eject_text_19x5.png
  assets/icons/Infrared/fast_backward_19x20.png
  assets/icons/Infrared/fast_backward_hover_19x20.png
  assets/icons/Infrared/fast_backward_text_19x6.png
  assets/icons/Infrared/fast_f_19x20.png
  assets/icons/Infrared/fast_f_hover_19x20.png
  assets/icons/Infrared/fast_f_text_19x6.png
  assets/icons/Infrared/ok_19x20.png
  assets/icons/Infrared/ok_hover_19x20.png
  assets/icons/Infrared/ok_text_19x5.png
  assets/icons/Infrared/subtitle_19x20.png
  assets/icons/Infrared/subtitle_hover_19x20.png
  assets/icons/Infrared/subtitle_text_19x5.png
  targets/f7/api_symbols.csv
Labels: feature

#253 New (and improved!) "Updating" Icon
  CHANGELOG.md
  assets/icons/Update/Updating_32x40.png
Labels: feature

#256 Sub-GHz: Nexus-TH weather station protocol improvements on detection
  CHANGELOG.md
  lib/subghz/protocols/nexus_th.c
Labels: enhancement

#255 Infrared: Add option to "Load from Library File" for Universal Remotes
  CHANGELOG.md
  applications/main/infrared/infrared_brute_force.c
  applications/main/infrared/infrared_brute_force.h
  applications/main/infrared/infrared_cli.c
  applications/main/infrared/scenes/common/infrared_scene_universal_common.c
  applications/main/infrared/scenes/infrared_scene_config.h
  applications/main/infrared/scenes/infrared_scene_start.c
  applications/main/infrared/scenes/infrared_scene_universal.c
  applications/main/infrared/scenes/infrared_scene_universal_from_file.c
Labels: feature

#259 JavaScript: Add I2C support
  CHANGELOG.md
  applications/system/js_app/application.fam
  applications/system/js_app/examples/apps/Scripts/Examples/i2c.js
  applications/system/js_app/modules/js_i2c.c
  applications/system/js_app/types/i2c/index.d.ts
Labels: feature

#262 Sub-GHz: Added Vauno-EN8822 weather station
  CHANGELOG.md
  applications/debug/unit_tests/resources/unit_tests/subghz/vauno_en8822c.sub
  applications/debug/unit_tests/resources/unit_tests/subghz/vauno_en8822c_raw.sub
  applications/debug/unit_tests/tests/subghz/subghz_test.c
  lib/subghz/protocols/protocol_items.c
  lib/subghz/protocols/protocol_items.h
  lib/subghz/protocols/vauno_en8822c.c
  lib/subghz/protocols/vauno_en8822c.h
Labels: feature

#263 Update ReadMe.md
  ReadMe.md
Labels: documentation

#264 IR: Update universal bluray remote
  CHANGELOG.md
  applications/main/infrared/resources/infrared/assets/bluray_dvd.ir
Labels: enhancement

#267 NFC: Improve URI decoding in NDEF parser
  CHANGELOG.md
  applications/main/nfc/plugins/supported_cards/ndef.c
Labels: enhancement

#272 JavaScript: SPI implementation
  CHANGELOG.md
  applications/system/js_app/application.fam
  applications/system/js_app/examples/apps/Scripts/Examples/spi.js
  applications/system/js_app/modules/js_spi.c
  applications/system/js_app/types/spi/index.d.ts
Labels: feature

#265 NFC: NDEF parser Mifare Classic support, protocol-agnostic refactor and more improvements
  CHANGELOG.md
  applications/main/nfc/application.fam
  applications/main/nfc/plugins/supported_cards/ndef.c
  targets/f7/api_symbols.csv
Labels: feature

#275 NFC: NDEF SmartPoster support
  CHANGELOG.md
  applications/main/nfc/plugins/supported_cards/ndef.c
Labels: feature

#278 NFC: NDEF Parser SLIX support
  CHANGELOG.md
  applications/main/nfc/application.fam
  applications/main/nfc/plugins/supported_cards/ndef.c
Labels: feature
