Repository Next-Flip/Momentum-Firmware, pull requests merged in 2024-11, with the labels that each got.

#290 JS: Add illegalSymbols prop for gui/text_input
  CHANGELOG.md
  applications/system/js_app/examples/apps/Scripts/Examples/gui.js
  applications/system/js_app/examples/apps/Scripts/interactive.js
  applications/system/js_app/js_modules.c
  applications/system/js_app/modules/js_gui/text_input.c
  applications/system/js_app/packages/fz-sdk/gui/text_input.d.ts
  applications/system/js_app/packages/fz-sdk/package.json
Labels: feature

#291 FBT: Optimize icons blob -4KB DFU, scrub unused icons
  .github/workflows/build.yml
  CHANGELOG.md
  applications/main/nfc/application.fam
  applications/settings/about/application.fam
  applications/settings/power_settings_app/application.fam
  applications/settings/storage_settings/application.fam
  applications/system/js_app/application.fam
  assets/SConscript
  assets/icons/Infrared/Play_25x27.png
  assets/icons/Infrared/Play_hvr_25x27.png
  assets/icons/Infrared/hourglass0_24x24.png
  assets/icons/Infrared/hourglass1_24x24.png
  assets/icons/Infrared/hourglass2_24x24.png
  assets/icons/Infrared/hourglass3_24x24.png
  assets/icons/Infrared/hourglass4_24x24.png
  assets/icons/Infrared/hourglass5_24x24.png
  assets/icons/Infrared/hourglass6_24x24.png
  assets/icons/PIN/Pin_cell_13x13.png
  scripts/assets.py
  scripts/check_unused_icons.py
  scripts/fbt_tools/fbt_assets.py
  scripts/fbt_tools/fbt_extapps.py
  targets/f7/api_symbols.csv
  targets/f7/target.json
Labels: bugfix

#295 Asset Packer: Fix font terminator causing freezes/crashes
  CHANGELOG.md
  scripts/asset_packer.py
Labels: bugfix

#296 Settings: Add warnings for settings you shouldn't touch
  CHANGELOG.md
  applications/main/subghz/subghz_i.c
  applications/services/cli/cli.c
  applications/services/loader/loader.c
  applications/services/loader/loader_menu_storage.c
  applications/settings/system/system_settings.c
Labels: enhancement

#311 Desktop: Fixed Wardriving animation design
  CHANGELOG.md
  assets/dolphin/external/L1_Wardriving_128x64/frame_0.png
  assets/dolphin/external/L1_Wardriving_128x64/frame_1.png
  assets/dolphin/external/L1_Wardriving_128x64/frame_2.png
  assets/dolphin/external/L1_Wardriving_128x64/frame_3.png
  assets/dolphin/external/L1_Wardriving_128x64/frame_4.png
  assets/dolphin/external/L1_Wardriving_128x64/frame_5.png
  assets/dolphin/external/L1_Wardriving_128x64/frame_6.png
  assets/dolphin/external/L1_Wardriving_128x64/frame_7.png
  assets/dolphin/external/L1_Wardriving_128x64/meta.txt
Labels: bugfix

#304 feat(hid_ptt): support Gather
  CHANGELOG.md
  applications/system/hid_app/views/hid_ptt.c
Labels: enhancement
