Repository Next-Flip/Momentum-Firmware, pull requests merged in 2024-03, with the labels that each got.

#1 fixing always updating rainbow mode
  lib/drivers/rgb_backlight.c
  lib/drivers/rgb_backlight.h
Labels: bugfix

#6 Expansion: Add is_connected API to check for VGM
  applications/services/expansion/expansion.c
  applications/services/expansion/expansion.h
  applications/services/expansion/expansion_worker.c
  applications/services/expansion/expansion_worker.h
  targets/f7/api_symbols.csv
Labels: enhancement

#14 JS: Add BLE Beacon, Keyboard, Math modules
  applications/system/js_app/application.fam
  applications/system/js_app/examples/apps/Scripts/blebeacon.js
  applications/system/js_app/examples/apps/Scripts/keyboard.js
  applications/system/js_app/examples/apps/Scripts/math.js
  applications/system/js_app/examples/apps/Scripts/submenu.js
  applications/system/js_app/modules/js_blebeacon.c
  applications/system/js_app/modules/js_keyboard.c
  applications/system/js_app/modules/js_math.c
  applications/system/js_app/modules/js_submenu.c
Labels: feature

#45 MNTM asset pack - Adding SubGhz assets
  assets/packs/Momentum/Icons/SubGhz/Fishing_123x52.png
  assets/packs/Momentum/Icons/SubGhz/Scanning_123x52.png
Labels: enhancement

#56 JS: Add widget module
  applications/system/js_app/application.fam
  applications/system/js_app/examples/apps/Scripts/widget-js.fxbm
  applications/system/js_app/examples/apps/Scripts/widget.js
  applications/system/js_app/modules/js_widget.c
Labels: feature

#62 NFC MBTA CharlieCard parsing plugin
  applications/main/nfc/application.fam
  applications/main/nfc/plugins/supported_cards/charliecard.c
Labels: feature
