Repository Next-Flip/Momentum-Firmware, pull requests merged in 2024-07, with the labels that each got.

#156 Infrared: Correct Samsung.ir CH+ command
  applications/main/infrared/resources/infrared/Samsung.ir
Labels: bugfix

#157 RFID: Add blank InstaFob detection
  lib/lfrfid/protocols/lfrfid_protocols.c
  lib/lfrfid/protocols/lfrfid_protocols.h
  lib/lfrfid/protocols/protocol_insta_fob.c
  lib/lfrfid/protocols/protocol_insta_fob.h
Labels: feature

#137 NFC: Add parser for CSC Service Works Reloadable Cash Card
  CHANGELOG.md
  applications/main/nfc/application.fam
  applications/main/nfc/plugins/supported_cards/csc.c
Labels: feature

#159 Infrared: Added missing Koro Box entry to TV universal remote
  CHANGELOG.md
  applications/main/infrared/resources/infrared/assets/tv.ir
Labels: enhancement

#161 Main Menu: Unload when opening apps
  applications/main/momentum_app/momentum_app.c
  applications/main/momentum_app/scenes/momentum_app_scene_interface_mainmenu.c
  applications/main/momentum_app/scenes/momentum_app_scene_interface_mainmenu_add.c
  applications/main/momentum_app/scenes/momentum_app_scene_interface_mainmenu_add_main.c
  applications/main/momentum_app/scenes/momentum_app_scene_interface_mainmenu_reset.c
  applications/services/loader/loader.c
  applications/services/loader/loader_i.h
  applications/services/loader/loader_menu.c
  applications/services/loader/loader_menu.h
  applications/services/loader/loader_menuapp.h
Labels: enhancement

#164 Asset Packs: Optimize icon loader
  applications/main/momentum_app/momentum_app.h
  applications/services/gui/canvas.c
  applications/services/gui/icon_animation.c
  applications/services/gui/icon_i.h
  applications/services/loader/loader_menu.h
  furi/flipper.c
  lib/momentum/asset_packs.c
  lib/momentum/asset_packs.h
  lib/momentum/asset_packs_i.h
  lib/momentum/assets.c
  lib/momentum/momentum.h
  lib/momentum/namespoof.c
  lib/momentum/settings.c
  lib/momentum/settings.h
  lib/momentum/settings_i.h
  scripts/assets.py
  targets/f7/api_symbols.csv
Labels: enhancement

#165 Infrared: Remove duplicates from LED universal remote
  applications/main/infrared/resources/infrared/assets/led.ir
Labels: bugfix

#167 Infrared: Remove duplicates from Projectors universal remote
  CHANGELOG.md
  applications/main/infrared/resources/infrared/assets/fans.ir
  applications/main/infrared/resources/infrared/assets/projectors.ir
Labels: bugfix

#170 Sub-GHz: Added EmosE601x and Acurite 5in1 protocols from WS app
  CHANGELOG.md
  lib/subghz/protocols/acurite_5n1.c
  lib/subghz/protocols/acurite_5n1.h
  lib/subghz/protocols/emos_e601x.c
  lib/subghz/protocols/emos_e601x.h
  lib/subghz/protocols/protocol_items.c
  lib/subghz/protocols/protocol_items.h
Labels: feature
