Repository Next-Flip/Momentum-Firmware, pull requests merged in 2024-09, with the labels that each got.

#201 NFC: Saflok parser Date Rollover
  applications/main/nfc/plugins/supported_cards/saflok.c
Labels: bugfix

#225 Add API to enforce ISO15693 mode
  CHANGELOG.md
  lib/nfc/nfc.c
  lib/nfc/nfc.h
  lib/signal_reader/parsers/iso15693/iso15693_parser.c
  lib/signal_reader/parsers/iso15693/iso15693_parser.h
  targets/f7/api_symbols.csv
  targets/f7/furi_hal/furi_hal_nfc_iso15693.c
  targets/furi_hal_include/furi_hal_nfc.h
Labels: enhancement

#216 Update mf_classic_dict.nfc
  CHANGELOG.md
  applications/main/nfc/resources/nfc/assets/mf_classic_dict.nfc
Labels: enhancement

#217 Add Bresser 3CH weather station
  CHANGELOG.md
  applications/debug/unit_tests/resources/unit_tests/subghz/bresser_3ch.sub
  applications/debug/unit_tests/resources/unit_tests/subghz/bresser_3ch_raw.sub
  applications/debug/unit_tests/tests/subghz/subghz_test.c
  lib/subghz/protocols/bresser_3ch.c
  lib/subghz/protocols/bresser_3ch.h
  lib/subghz/protocols/protocol_items.c
  lib/subghz/protocols/protocol_items.h
Labels: feature

#215 Show satellites with an icon
  CHANGELOG.md
  applications/main/subghz/scenes/subghz_scene_decode_raw.c
  applications/main/subghz/scenes/subghz_scene_receiver.c
  applications/main/subghz/subghz_history.c
  applications/main/subghz/subghz_history.h
  applications/main/subghz/views/receiver.c
  applications/main/subghz/views/receiver.h
  assets/icons/SubGhz/Sats_6x9.png
  targets/f7/api_symbols.csv
Labels: enhancement

#203 SmartRider NFC Parser
  CHANGELOG.md
  applications/main/nfc/application.fam
  applications/main/nfc/plugins/supported_cards/smartrider.c
Labels: feature

#237 Add support for NTAG I2C Plus 1k and 2k chips
  CHANGELOG.md
  applications/main/nfc/plugins/supported_cards/ndef.c
Labels: enhancement
