Repository Next-Flip/Momentum-Firmware, pull requests merged in 2025-01, with the labels that each got.

#325 BadKB: Added german Mac keyboard Layout
  CHANGELOG.md
  applications/main/bad_kb/resources/badusb/assets/layouts/de-DE-mac.kl
Labels: feature

#348 IR: update universal bluray remote
  CHANGELOG.md
  applications/main/infrared/resources/infrared/assets/bluray_dvd.ir
Labels: enhancement

#339 Main Menu: Fix MNTM style battery percent off by 1
  CHANGELOG.md
  applications/services/gui/modules/menu.c
Labels: bugfix

#343 Lockscreen: Separate 'Allow RPC While Locked' for USB/BLE
  CHANGELOG.md
  applications/main/momentum_app/scenes/momentum_app_scene_interface_lockscreen.c
  applications/services/desktop/desktop.c
  applications/services/rpc/rpc.c
  lib/momentum/settings.c
  lib/momentum/settings.h
Labels: enhancement

#342 CLI: Add 'clear' command and command suggestion
  CHANGELOG.md
  applications/services/cli/cli.c
  applications/services/cli/cli_commands.c
Labels: feature

#357 Main Menu: Fixes scrollable text in CoverFlow
  applications/services/gui/modules/menu.c
Labels: bugfix

#359 Main Menu: Add 'Menu Style' submenu
  CHANGELOG.md
  applications/main/momentum_app/scenes/momentum_app_scene_config.h
  applications/main/momentum_app/scenes/momentum_app_scene_interface_graphics_pack.c
  applications/main/momentum_app/scenes/momentum_app_scene_interface_mainmenu.c
  applications/main/momentum_app/scenes/momentum_app_scene_interface_mainmenu_style.c
Labels: enhancement

#358 IR: Update universals
  CHANGELOG.md
  applications/main/infrared/resources/infrared/assets/audio.ir
  applications/main/infrared/resources/infrared/assets/bluray_dvd.ir
  applications/main/infrared/resources/infrared/assets/tv.ir
  scripts/fix_ir_universals.py
Labels: enhancement

#360 IR: Easy Learn [Bugfix]
  applications/main/infrared/scenes/infrared_scene_start.c
Labels: bugfix
